### ISSUE TITLE
오류메세지 확인 부탁드릴게요

### ISSUE THREAD

**Issue by minminle2** [vEduardovich/dodari#9]
start_windows 실행하면 

대용량 번역기 도다리를 시작합니다.
잠시만 기다려주세요..
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.29.0, however version 5.0.1 is available, please upgrade.

이렇게 나오면서 

http://127.0.0.1:7861/ 

이 도다리 웹페이지가 열려요.
여기서 순서1 파일등록하기에 파일을 끌어올리면

대용량 번역기 도다리를 시작합니다.
잠시만 기다려주세요..
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.29.0, however version 5.0.1 is available, please upgrade.
--------
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Downloads\dodari-main\venv\Lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\dodari-main\venv\Lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

이렇게 오류가 cmd창에 나타나고 웹페이지에서는 
error
Connection errored out.
이렇게 나와요.

챗gpt에 오류상황 올려서 버전안맞는거 맞추기도하고 없는거 설치도 새로이 하고 이것저것 하라는거는 다 해봤는데도 
제자리걸음이에요 ㅠㅠ 

확인 부탁드릴게요~

**Comment by vEduardovich** [comment]
이슈등록 감사합니다!
완전히 처음보는 에러 메시지라 바로 해결은 어렵겠네요.
계속 알아보고 있으니 잠시만 기다려주세요.

**Comment by vEduardovich** [comment]
아. 맞습니다.
지금 그램 노트북에서 확인해보니
그동안 잘 돌아가던 도다리가 갑자기 위와 똑같은 메시지를 뱉으며 에러가 나네요.
제 환경에서 같은 메시지가 나오니 해결이 훨씬 쉬워질거 같습니다.
조금만 더 기다려주세요.

**Comment by vEduardovich** [comment]
이유를 찾아냈습니다.
그놈의 지긋지긋한ㅠ gradio가 또 문제를 일으켰네요.
해결 방법을 정리하고 있으니 조금만 더 기다려주세요

**Comment by vEduardovich** [comment]
덕분에 문제를 해결하여 github에 업로드 하였습니다.

해결 방법에는 두가지가 있습니다.
첫번째 방법은, github에서 도다리를 다시 다운로드 받은 후 start_windows.bat 를 실행하셔서 처음부터 다시 받고 시작하시는 겁니다. 아래 복잡한 방법에 비해 시간은 오래 걸리지만 확실히 간단한 방법입니다.

두번째 방법은, 복잡하지만 빠르게 수정할수 있습니다.
1. dodari가 설치된 메인 폴더에서 터미널을 연후, 아래의 스크립트를 입력하셔서 venv가상환경으로 진입합니다. 
.\venv\Scripts\activate.bat
2. 다음 gradio의 버전을 아래와 같이 4.44.1 로 바꿉니다. 5.0이상으로 바꾸시면 안됩니다. 그건 또 에러가 날겁니다.
pip install --upgrade gradio==4.44.1
3. 이제 다시 dodari 메인 폴더로 이동하신 후 아래와 같이 도다리를 실행하시면 됩니다.
python dodari.py

버전 충돌 문제를 알려주셔서 한번 더 감사드립니다.

**Comment by minminle2** [comment]
감사합니다~ 두번째방법대로 하니까 잘되네요~~
근데 혹시 pdf파일은 번역이 안될까요?? epub txt srt 만 되더라고요..
pdf파일도 보면 이지미로 되어있는것은 ocr판독해야하니까 안되더라도 문자로 만들어진pdf파일은 번역 되더라고요.
구글번역도 pdf 파일이 번역이 되고요.
혹시나 해서 여쭤봐요~~
무튼 너무 감사합니다

**Comment by vEduardovich** [comment]
해결이 되셨다니 정말로 기쁩니다!!!

pdf는 구조적 문서라기보다 디자인 문서에 가까워서 
텍스트나 이미지만 쭉 뽑아내는 것은 일반 pdf뿐만 아니라 이미지로 만든 pdf도 여러 모듈들을 사용해 간단하게 뽑을수는 있어요.
그런데 문제는 이렇게 뽑아낸 텍스트와 이미지를 다시 원래의 pdf형식으로 만들어내기가 꽤 어려워요.
pdf는 같은 pdf라도 보안에 따라 내부적으로 여러가지 pdf가 있고 여러가지 요소들로 복잡하게 구조되어 있어요.

그래서 구글이나 deepL로 pdf를 번역해도 레이아웃이 엉망이 되는 경우가 많습니다. (그래도 걔네들은 인력이 많으니 어느정도 가능하게 만들었죠)
예전에 pdf를 html과 같은 다른 구조적 언어로 바꿔본적이 있는데 이것도 쉽지가 않더라고요. 깨지지 않는 레이아웃을 만드는데 너무 많은 시간이 투입되어 중간에 그만뒀적이 있습니다 ㅠ

지금 rag와 페르소나 채팅이 포함된 도다리 확장 앱을 만들고 있는데
이번에 시간적 여유가 된다면 pdf 번역기능에 한번 더 도전해보겠습니다.

도다리를 사용해주셔서 감사합니다.
